 name: Deploy-frontend-to-stage
on: 
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  any-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0 # Important for the next step to have the complete git history
          
      - name: Check for version change
        id: version-changed
        uses: Endbug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true # Search for changes in the last commit
    
      - name: Hello-step
        run: echo "Hello World"
